### ISSUE TITLE
Bug when use default algorithm in hmac:new function 

### ISSUE THREAD

**Issue by starsz** [jkeys089/lua-resty-hmac#14]
Hello, when i use hmac:new("xxx"). I found that there was a mistake in your code.

That  in your code. hmac.lua:123 

```
 local _hash_algo = hash_algo or hashes.md5
```

I think it should be

```
 local _hash_algo = hash_algo or hashes.MD5
```

**Comment by jkeys089** [comment]
@starsz Thank you for the report!
