### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by membphis** [jkeys089/lua-resty-hmac#25]
@jkeys089 you can create a new tag, then I'll submit a new luarocks file

**Comment by jkeys089** [comment]
@membphis thanks again for your contribution! I believe everything is working as expected now (see: https://luarocks.org/modules/jkeys089/lua-resty-hmac-ffi). Please feel free to re-open this issue if needed.

**Comment by membphis** [comment]
@jkeys089 you can delete it from your luarocks account, and then reuploaded it again.

I have removed `lua-resty-hmac-ffi` from my account right now.

**Comment by jkeys089** [comment]
@membphis ok, I've removed / re-uploaded. Hopefully that helps!
