### ISSUE TITLE
luarocks: need to recreate again, make it as `root` project

### ISSUE THREAD

**Issue by membphis** [jkeys089/lua-resty-hmac#29]
![image](https://user-images.githubusercontent.com/6814606/93972522-fe3b8980-fda4-11ea-8c0d-9cde24801bb4.png)

**Comment by membphis** [comment]
@jkeys089 we can talk here

**Comment by jkeys089** [comment]
@membphis it seems to be working as expected now.

**Comment by membphis** [comment]
yes, it works fine now. And I make a try right now, it can install as expected.

![image](https://user-images.githubusercontent.com/6814606/94107877-e29db500-fe70-11ea-9065-9309e40cbff7.png)
