### ISSUE TITLE
how to use sha256 without key

### ISSUE THREAD

**Issue by C4o** [jkeys089/lua-resty-hmac#30]
I set the KEY to "", but the result is not right...How can i do..

**Comment by jkeys089** [comment]
@C4o using an empty key should work fine.
E.g.
```lua
ngx.say(hmac:new("", hmac.ALGOS.SHA256):final("hello, world!", true))
  -- output: "2f0dc4b94797ef8e149c247a6eb13df7a8f4aaf8eea19dfb548f7f80d25cef0c"
```

**Comment by C4o** [comment]
but the output should be 68e656b251e67e8358bef8483ab0d51c6619f3e7a1a9f0e75838d41ff368f728...
the following output of golang and a online calc website are the same...
https://cmd5.com/hash.aspx?s=hello,%20world!

```go
package main

import (
	"crypto/sha256"
	"fmt"
)

func main() {
	fmt.Printf( "%x" , sha256.New().Sum([]byte("hello, world!")))
}
```

**Comment by jkeys089** [comment]
@C4o in your example you've computed the sha-256 _**hash**_. This lib computes [HMAC](https://en.wikipedia.org/wiki/HMAC). The comparable Go code would look like https://play.golang.org/p/mmzDteED9CL.

**Comment by C4o** [comment]
sorry...
