### ISSUE TITLE
make friends with you @jkeys089

### ISSUE THREAD

**Issue by membphis** [jkeys089/lua-resty-hmac#33]
hi:

I am yuansheng, the PMC of Apache APISIX.

We are using this library in APISIX now.

My email: membphis@apache.org , I want to make friends with you.

Waiting for your response.

**Comment by jkeys089** [comment]
@membphis 👋  -- I'm glad to hear the code is useful to you. If you have any ideas to improve things I'm always happy to collaborate. Also, APISIX looks very cool! Great work!

**Comment by membphis** [comment]
I sent you an email right now. Many thx for your job.
