### ISSUE TITLE
Push on OPM ?

### ISSUE THREAD

**Issue by tsunammis** [jkeys089/lua-resty-hmac#4]
Hello,

Currently, I'm using your library for an another project, I would like to import it from [OPM](https://opm.openresty.org/).

Could you push your library on it please ?

Thank you.

**Comment by jkeys089** [comment]
Yes, I've been meaning to take a look at that. I'll let you know when it is available on OPM.

**Comment by jkeys089** [comment]
lua-resty-hmac is now on OPM under `jkeys089/lua-resty-hmac`.

**Comment by tsunammis** [comment]
Great @jkeys089 Thanks a lot.
