### ISSUE TITLE
Add this as a module in LuaRocks?

### ISSUE THREAD

**Issue by cdbattags** [jkeys089/lua-resty-hmac#9]
Mind uploading this to LuaRocks under your own name?

And possibly add all previous versions from the last owner as well? Trying to get this updated for https://github.com/zmartzone/lua-resty-openidc! I did the same with https://github.com/cdbattags/lua-resty-jwt.

Refer to https://github.com/luarocks/luarocks-site/issues/133 for help.

**Comment by jkeys089** [comment]
I don't personally use LuaRocks but I'm not against making this project available there. However, it looks like the previous project published to LuaRocks under the lua-resty-hmac name has a much different API. Also, I don't think I would be interested in taking over responsibility for publishing old versions of someone else's project. If we start publishing to LuaRocks we should probably choose a different name. If you think this could be useful please feel free to submit a PR with any LuaRocks requirements and some brief instructions I could follow to publish to LuaRocks.

**Comment by cdbattags** [comment]
Yeah, that's what had me confused. I could have sworn this was a fork of that repo just from a cursory glance so that is 100% my bad.

Well hmm, then how is the project https://github.com/zmartzone/lua-resty-openidc using this package? This was initially how I got confused because they are using LuaRocks for all other packages besides this one. I see a link to here in the `dist.ini`?

**Comment by jkeys089** [comment]
`dist.ini` is used for [opm](https://github.com/openresty/opm).
